# Generated by Django 4.2.5 on 2023-11-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('proyecto', models.CharField(max_length=50)),
                ('estado_activo', models.CharField(max_length=50)),
                ('ordenar_por', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_responsable', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('estado_activo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('activo_titulo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
